# Generated by Django 2.2.5 on 2019-09-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parentID',
        ),
    ]
