# Generated by Django 2.2.5 on 2019-09-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Category'),
        ),
    ]
