# Generated by Django 2.2.5 on 2019-09-26 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
    ]
