# Generated by Django 2.2.5 on 2019-09-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190926_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
    ]
