# Generated by Django 2.2.5 on 2019-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190926_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parentID',
            field=models.IntegerField(null=True),
        ),
    ]
