# Generated by Django 2.2.5 on 2019-09-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190926_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parentID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
