# Generated by Django 2.2.5 on 2019-10-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_contacts',
            name='phone',
        ),
    ]
